# Generated by Django 5.2.8 on 2026-06-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('service', models.CharField(choices=[('custom-platform', 'Custom Web Platform'), ('dashboard', 'Dashboard / Data System'), ('automation', 'AI / Automation'), ('landing', 'Landing Page / Campaign System'), ('cloud', 'Cloud / Deployment'), ('consulting', 'Consulting')], max_length=40)),
                ('budget', models.CharField(blank=True, choices=[('under-1000', 'Under $1,000'), ('1000-3000', '$1,000 - $3,000'), ('3000-7500', '$3,000 - $7,500'), ('7500-plus', '$7,500+'), ('not-sure', 'Not sure yet')], max_length=40)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact submission',
                'verbose_name_plural': 'Contact submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
