# Generated by Django 5.2.8 on 2026-06-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_contactsubmission_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='source',
            field=models.CharField(choices=[('contact_form', 'Contact form'), ('chat', 'AI chat')], db_index=True, default='contact_form', max_length=20),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', max_length=20),
        ),
    ]
