# Generated by Django 5.2.8 on 2026-06-03 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_contactsubmission_source_contactsubmission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Public key used by the embed widget.', unique=True)),
                ('name', models.CharField(max_length=160)),
                ('system_prompt', models.TextField(help_text='What the agent should know about this business: services, pricing, FAQ.')),
                ('greeting', models.CharField(blank=True, help_text='First message the widget shows. Leave blank for a default.', max_length=400)),
                ('notify_email', models.EmailField(max_length=254)),
                ('allowed_origins', models.TextField(blank=True, help_text='Comma-separated domains allowed to embed the widget, e.g. example.com, www.example.com')),
                ('primary_color', models.CharField(default='#34d6c8', max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='landing.client'),
        ),
    ]
