# Generated by Django 5.2.8 on 2026-06-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_client_enable_bookings_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='source',
            field=models.CharField(choices=[('contact_form', 'Contact form'), ('chat', 'AI chat'), ('signup', 'Agent signup')], db_index=True, default='contact_form', max_length=20),
        ),
    ]
