# Generated by Django 5.2.8 on 2026-06-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_alter_contactsubmission_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='onboarding_sent',
            field=models.BooleanField(default=False),
        ),
    ]
