# Generated by Django 5.2.8 on 2026-06-06 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_dominio_onboarding_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='landing.client'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='landing.client'),
        ),
    ]
