# Generated by Django 5.2.8 on 2026-06-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_alter_membership_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
