# Generated by Django 5.2.8 on 2026-06-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_contactsubmission_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='surface_color',
            field=models.CharField(default='#12304a', max_length=9, verbose_name='Background color'),
        ),
        migrations.AlterField(
            model_name='client',
            name='primary_color',
            field=models.CharField(default='#34d6c8', max_length=9, verbose_name='Accent color'),
        ),
    ]
