# Generated by Django 5.2.8 on 2026-06-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_client_surface_color_alter_client_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='header_color',
            field=models.CharField(default='#0c2132', max_length=9, verbose_name='Header color'),
        ),
    ]
