# Generated by Django 5.2.8 on 2026-07-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_client_header_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='page_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
