# Generated by Django 5.2.8 on 2026-07-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_contactsubmission_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='service',
            field=models.CharField(choices=[('operational-platform', 'Custom Operational Platforms'), ('data-dashboards', 'Data, Dashboards & Reporting Systems'), ('ai-automation', 'AI, Automation & Workflow Optimization'), ('landing-campaigns', 'Landing Pages, Forms & Campaign Systems'), ('consulting', 'Product Strategy & Technical Consulting'), ('it-services', 'Technology Management & IT Support')], max_length=40),
        ),
    ]
