# Generated by Django 5.2.8 on 2026-07-24 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_alter_contactsubmission_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='daily_message_cap',
            field=models.PositiveIntegerField(default=300, help_text='Max chat messages per day for this agent (per-tenant quota).'),
        ),
        migrations.AddField(
            model_name='client',
            name='notify_channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'Email + WhatsApp'), ('sms', 'Email + SMS')], default='email', max_length=12),
        ),
        migrations.AddField(
            model_name='client',
            name='notify_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_language',
            field=models.CharField(choices=[('es', 'Español (PR)'), ('en', 'English')], default='es', max_length=5),
        ),
        migrations.AddField(
            model_name='client',
            name='retention_months',
            field=models.PositiveSmallIntegerField(default=12, help_text='Months to keep chat conversations before automatic purge.'),
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('org_admin', 'Administrador'), ('agent', 'Agente')], default='org_admin', max_length=12),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('result', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='landing.client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_session', models.CharField(db_index=True, max_length=64)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('state', models.CharField(choices=[('active', 'Activa'), ('escalated', 'Escalada'), ('followup', 'En seguimiento'), ('closed_resolved', 'Cerrada — resuelta'), ('closed_unresolved', 'Cerrada — no resuelta'), ('abandoned', 'Abandonada'), ('blocked', 'Bloqueada')], db_index=True, default='active', max_length=20)),
                ('escalation_reason', models.CharField(blank=True, max_length=300)),
                ('config_version', models.CharField(blank=True, max_length=16)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='landing.client')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='landing.contactsubmission')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=12)),
                ('content', models.TextField()),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='landing.conversation')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'Texto'), ('faq', 'Preguntas frecuentes (P: / R:)'), ('url', 'Página web (URL)')], default='text', max_length=10)),
                ('title', models.CharField(max_length=160)),
                ('origin', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True, help_text='Texto o FAQ. Para URL se llena automáticamente al procesar.')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('error', 'Error'), ('archived', 'Archivada')], db_index=True, default='draft', max_length=10)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('review_by', models.DateField(blank=True, help_text='Fecha en que este contenido debe revisarse.', null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to='landing.client')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='landing.knowledgesource')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('scale', 'Scale'), ('custom', 'Custom')], max_length=20)),
                ('period', models.CharField(choices=[('monthly', 'Mensual'), ('annual', 'Anual')], default='monthly', max_length=10)),
                ('method', models.CharField(choices=[('stripe', 'Stripe'), ('ath_movil', 'ATH Móvil'), ('manual', 'Manual')], default='stripe', max_length=12)),
                ('status', models.CharField(choices=[('incomplete', 'Incompleta'), ('active', 'Activa'), ('past_due', 'Pago vencido'), ('canceled', 'Cancelada')], db_index=True, default='incomplete', max_length=12)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=80)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='landing.client')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='landing.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('slot_minutes', models.PositiveSmallIntegerField(default=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='landing.client')),
            ],
            options={
                'ordering': ['weekday', 'open_time'],
                'constraints': [models.UniqueConstraint(fields=('client', 'weekday'), name='uniq_availability_per_weekday')],
            },
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('client', 'widget_session'), name='uniq_conversation_per_session'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'position'), name='uniq_message_position'),
        ),
    ]
