# Generated by Django 5.2.8 on 2026-07-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0018_processedwebhookevent_client_daily_message_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
