# Generated by Django 5.2.8 on 2026-08-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0019_booking_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='install_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='live_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='platform',
            field=models.CharField(blank=True, choices=[('wordpress', 'WordPress'), ('wix', 'Wix'), ('squarespace', 'Squarespace'), ('shopify', 'Shopify'), ('godaddy', 'GoDaddy Website Builder'), ('html', 'HTML / sitio a la medida'), ('other', 'Otra plataforma'), ('unknown', 'No sé')], max_length=40),
        ),
        migrations.AddField(
            model_name='client',
            name='setup_status',
            field=models.CharField(choices=[('pending', 'Pendiente de instalación'), ('live', 'En vivo')], default='live', max_length=12),
        ),
        migrations.AddField(
            model_name='client',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='widget_last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='checkout_session_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
