# Generated by Django 5.2.8 on 2026-08-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_processedwebhookevent_handled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='widget_token',
            field=models.CharField(blank=True, db_index=True, help_text='Secret the embedded widget sends to authenticate this tenant.', max_length=64),
        ),
    ]
