# Generated by Django 5.2.8 on 2026-08-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0022_client_widget_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='checkout_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
