# Generated by Django 5.2.17 on 2026-08-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0023_alter_subscription_checkout_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='initial_discount_cents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='initial_subtotal_cents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='initial_tax_cents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='initial_total_cents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='setup_fee_charged',
            field=models.BooleanField(default=False),
        ),
    ]
