# Generated by Django 5.2.17 on 2026-08-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0024_subscription_initial_discount_cents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
    ]
